---
become_override: False
ocp_username: opentlc-mgr
silent: False

_quay_project: quay
_quay_project_display: Red Hat Quay Registry
_quay_name: quay

# Access Credentials for Quay.io to pull Red Hat Quay
# Should be overwritten via base64 encoded Global Variables !!!
# reference https://access.redhat.com/solutions/3533201
_quay_dockerconfigjson: 'pull_secret'

# Quay Superuser
_quay_superuser_username: quayadmin
_quay_superuser_password: quaypassword
_quay_superuser_email: rhpds-admins@redhat.com

# Quay Config Password (username is always 'quayconfig'):
_quay_config_app_password: quayconfig

# Persistent Volumes Sizes
_quay_database_volume_size: 20Gi
_quay_volume_size: 20Gi
