---
- name: "Cleaning up temp directory"
  file: 
    path: "{{ repodir.path }}"
    state: absent

- name: "Gathering information about launched resources"
  k8s_facts:
    namespace: mig
    kind: Route
    name: migration
  register: mig_ui_route

- name: "Please note the following information..."
  debug: 
    msg: "Mig UI is launched at - {{ mig_ui_route.resources[0].spec.host }}"