---
- name: "Creating temp directory for operator repo"
  tempfile: 
    state: directory
    suffix: mig-operator
  register: repodir

- name: "Checking out operator repo"
  git:
    repo: "{{ mig_operator_repo }}"
    dest: "{{ repodir.path }}"
    
- name: "Applying variables"
  replace:
    path: "{{ repodir.path }}/controller.yml"
    regexp: "{{ item.pattern }}"
    replace: "{{ item.replace }}"
  loop:
    - { pattern: "migration_velero:.*", replace: "migration_velero: {{ mig_operator_deploy_velero }}" }
    - { pattern: "migration_controller:.*", replace: "migration_controller: {{ mig_operator_deploy_controller }}" }
    - { pattern: "migration_ui:.*", replace: "migration_ui: {{ mig_operator_deploy_ui }}" }
  when: not destroy

- name: "Applying mig cluster api endpoint"
  replace:
    path: "{{ repodir.path }}/controller.yml"
    regexp: "{{ item.pattern }}"
    replace: "{{ item.replace }}"
  loop:
    - { pattern: "#mig_ui_cluster_api_endpoint:.*", replace: "mig_ui_cluster_api_endpoint: {{ mig_operator_ui_cluster_api_endpoint }}" }
  when: not destroy and mig_operator_ui_cluster_api_endpoint != ''