= Velero Workload

== Overview

This is a workload for Velero, a backup / restore tool for Kubernetes. Following sections explain how to install this workload on your OCP cluster.

=== Purpose

Velero is used as a backup / restore tool by Red Hat Cluster Migration Tool.

This workload is used to perform demo migrations from OCP 3 to OCP 4 clusters. 

=== Deploy Velero using the workload

[source, bash]
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \ 
    -e"ocp_username=${OCP_USERNAME}" \ 
    -e"ocp_workload=ocp-workload-velero" \ 
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \d
    -e"student_userid=${ANSIBLE_USER}" \
    -e @./workload_vars.yaml \ <1>
    -e @./secret.yaml <2>
----
<1> Add all the variables marked as required from the following table in this file
<2> This is the same file you used while deploying OCP cluster using agnosticd. Optionally, include sensitive workload variables here.

=== Variables 

==== General 

|===
| Variable | Default Value | Description | Required

| velero_provider
| aws
| Backup & volume snapshot storage (Supported : aws, noobaa)
| No

| velero_namespace
| velero
| Name of the project in which Velero is launched 
| No

| velero_bsl_name
| default
| Name of backupstoragelocation resource created
| No

| velero_image
| quay.io/ocpmigrate/velero:fusor-dev
| Container image for Velero
| No

| velero_plugin_image
| quay.io/ocpmigrate/velero-plugin:latest
| Container image for mig-controller plugin
| No

| restic_pv_host_path
| /tmp/openshift.local.clusterup/openshift.local.volumes/pods
| Path where PVs are mounted
| No
|===

==== Storage Provider Variables

By default, this workload chooses AWS as the backend store for Velero. You may wish to choose other providers by overriding `velero_provider`. You need to include variables applicable to the provider you choose.

==== AWS

|===
| Variable | Default Value | Description | Required

| velero_aws_region
| -
| S3 region
| Yes

| velero_aws_bucket_name
| - 
| S3 bucket for backup storage
| Yes

| velero_aws_access_key_id
| -
| AWS key id
| Yes

| velero_aws_secret_access_key
| default
| AWS secret 
| Yes

| velero_aws_key_prefix
| velero
| Prefix for AWS keys 
| No

| velero_aws_secret_name
| cloud-credential
| Name for Kubernetes secret object created
| No

| velero_aws_bucket_cred_profile
| default
| Credential profile for AWS backup store
| No
|===


==== NooBaa

|===
| Variable | Default Value | Description | Required

| velero_noobaa_access_key_id
| -
| NooBaa key id
| Yes

| velero_noobaa_bucket_name
| - 
| NooBaa bucket for backup storage
| Yes

| velero_noobaa_secret_access_key
| -
| NooBaa secret 
| Yes

| velero_noobaa_service_url
| s3.noobaa.svc.cluster.local
| Service endpoint NooBaa
| No

| velero_noobaa_region
| noobaa
| S3 region in NooBaa
| No

| velero_noobaa_key_prefix
| velero
| Prefix for NooBaa keys 
| No

| velero_noobaa_secret_name
| cloud-credential
| Name for Kubernetes secret object created
| No

| velero_noobaa_bucket_cred_profile
| default
| Credential profile for NooBaa backup store
| No
|===


=== Delete Velero workload

[source, bash]
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=ocp-workload-velero" \ 
    -e"silent=False" \
    -e"guid=${GUID}" \ 
    -e"ACTION=remove" \
    -e"student_userid=${ANSIBLE_USER}" \
    -e @./secret.yaml \
    -e @./workload_vars.yaml
----
