---
- name: "{{ title }} custom CRD definitions"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('file', 'velero-prereqs.yml')}}"

- name: "Running tasks for {{ velero_provider }}"
  include_tasks: "./{{ velero_provider }}/main.yml"

- name: "{{ title }} velero deployment"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'velero-deployment.yml.j2')}}"

- name: "{{ title }} restic daemonset"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'restic-daemonset.yml.j2')}}"