= SQL Server Workload

== Overview

This is a workload for SQL Server with data directory mounted with a pv. Follow instructions in following sections to deploy this workload on your OCP cluster.

== Purpose

This workload is used by Red Hat Cluster Migration tool to demonstrate a migration of persistent volumes.

== Deploying SQL Server workload

[source, bash]
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \ 
    -e"ocp_username=${OCP_USERNAME}" \ 
    -e"ocp_workload=ocp-workload-velero" \ 
    -e"silent=False" \
    -e"guid=${GUID}" \
    -e"ACTION=create" \d
    -e"student_userid=${ANSIBLE_USER}" \
    -e @./secret.yaml <1>
----
<1> This is the same file you used while deploying OCP cluster using agnosticd. Optionally, include sensitive workload variables here.

SQL server uses default volume made available through a PVC. However, you may choose to create your own PV by setting `mssql_pv_provider`.

Supported providers are - default, nfs. 

=== Variables 

|===
| Variable | Default Value | Description | Required

| mssql_pv_provider
| default
| Type of PV to use
| No

| mssql_namespace
| mssql-persistent
| Namespace for the workload
| No

| mssql_image
| mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
| Container image for MsSQL server
| No

| mssql_sa_password
| P@ssw0rd1!
| Password for admin user
| No

| mssql_cpu_limit
| "2"
| CPU limit for MsSql
| No

| mssql_memory_limit
| "3Gi"
| Memory limit for MsSql
|

| mssql_port
| 1433
| SQL server port
| No

| mssql_volume_mount_name
| mssql-vol
| Name for pv resource
| No

| mssql_pvc_name
| mssql-pvc
| Name for pvc resource
| No

| mssql_app_name
| mssql-container
| Name for pod resource
| No

| mssql_secret_name
| mssql-secret
| Name for secret resource
| No

| mssql_service_name
| mssql-service
| Name for service resource
| No

| mssql_deployment_name
| mssql-deployment
| Name for deployment resource
| No
|===

==== PV Provider configuration

===== NFS

|===
| Variable | Default Value | Description | Required

| mssql_nfs_pv_server
| -
| NFS Server
| Yes

| mssql_nfs_pv_path
| - 
| Volume Path
| Yes

| mssql_nfs_pv_name
| mssql-pv
| Name of the pv
| No

| mssql_nfs_pv_storage_capacity
| 10Gi
| Storage capacity of nfs pv
| No
|===

=== Delete MsSQL Workload

[source, bash]
----
ansible-playbook -i "bastion.${GUID}.${BASE_DOMAIN}", ./ansible/configs/ocp-workloads/ocp-workload.yml \
    -e"ansible_ssh_private_key_file=${ANSIBLE_USER_KEY_FILE}" \
    -e"ansible_user=${ANSIBLE_USER}" \
    -e"ocp_username=${OCP_USERNAME}" \
    -e"ocp_workload=ocp-workload-velero" \ 
    -e"silent=False" \
    -e"guid=${GUID}" \ 
    -e"ACTION=remove" \
    -e"student_userid=${ANSIBLE_USER}" \
    -e @./secret.yaml 
----