---
- name: "{{ title }} CRs"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item) }}"
  with_items:
    - "namespace.yaml.j2"
    - "secret.yaml.j2"
    - "pvc.yaml.j2"
    - "deployment.yaml.j2"
    - "service.yaml.j2"
