---
- name: "{{ title }} CRs"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item) }}"
  with_items:
    - "namespace.yaml.j2"
    - "secret.yaml.j2"
    - "sa.yaml.j2"
    - "scc.yaml.j2"

- name: "{{ title }} storage"
  include_tasks: "./storage/{{ mssql_pv_provider }}/main.yml"

- name: "{{ title }} CRs"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item) }}"
  with_items:
    - "deployment.yaml.j2"
    - "service.yaml.j2"

- name: "{{ title }} MsSQL Sample App CRs"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'app/' + item) }}"
  with_items:
    - "deployment.yaml.j2"
    - "service.yaml.j2"
    - "route.yaml.j2"