---
- name: Update CORS Settings
  shell: "oc patch {{ item.kind }} {{ item.name }} -p '{{ lookup('template', item.patch_file) }}' --type=merge"
  loop:
    - { name: 'cluster', kind: 'kubeapiserver.operator', patch_file: './server.patch.yaml.j2' }
    - { name: 'cluster', kind: 'authentication.operator', patch_file: './authentication.patch.yaml.j2' }  
  when: not destroy



- name: Output resolved redirect route
  debug:
    msg: "{{ mig_ui_oauth_redirect_url }}"
  when: not destroy