---
- name: "{{ title }} route"
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item) | from_yaml }}"
  loop:
    - "route.yaml.j2"

- name: Generate random secret value for oauth client
  set_fact:
    mig_ui_oauth_secret: "{{ 99999999 | random | to_uuid | b64encode }}"
  when: not destroy

- name: Include variables from migmeta.yml
  include_vars: migmeta.yaml
  delegate_to: localhost

- name: Check if any MigClusters are present (looking for host MigCluster)
  set_fact:
    host_cluster_not_present: "{{ lookup('k8s', kind='MigCluster', namespace=mig_ui_namespace, api_version='migration.openshift.io/v1alpha1') | length == 0 }} "

- name: Create host cluster if its missing
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', 'host.migcluster.yaml.j2') | from_yaml }}"
  when: host_cluster_not_present or destroy

- name: Ensure no existing OAuthClients are present
  k8s:
    state: "absent"
    api_version: "oauth.openshift.io/v1"
    kind: OAuthClient
    name: "{{ mig_ui_oauth_client_id }}"

- name: "Set mig-ui object state={{ state }}"
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('template', item) | from_yaml }}"
  loop:
    - oauthclient.yaml.j2
    - configmap.yaml.j2
    - service.yaml.j2
    - deploymentconfig.yaml.j2