---
- name: "{{ ceph_workload_title }} common resources for Ceph"
  k8s:
    state: "{{ ceph_workload_state }}"
    definition: "{{ lookup('template', item) }}"
  loop:
    - "toolbox.yaml.j2"
    - "filesystem.yaml.j2"
  tags:
  - ceph_post_dep

- name: Installing storage classes
  shell: "/bin/bash /tmp/ceph-templates/files/{{ item }}"
  loop:
    - sc-cephfs.sh
    - sc-rbd.sh
  when: not ceph_workload_destroy

- name: Cleaning up storage classes
  shell: "{{ item }}"
  loop:
    - "oc delete secret csi-cephfs-secret -n default"
    - "oc delete sc csi-cephfs"
    - "oc delete secret csi-rbd-secret -n default"
    - "oc delete sc csi-rbd"
  ignore_errors: yes
  when: ceph_workload_destroy

- name: Cleaning up leftover directories on nodes
  shell: "/bin/bash /tmp/ceph-templates/files/cleanup.sh"
  ignore_errors: yes
  when: ceph_workload_destroy

- name: Deleting templates
  file:
    path: /tmp/ceph-templates
    state: absent